# The URL the site will be built for
#base_url = "http://127.0.0.1:1111/"
# github page
#base_url = "https://grelot.github.io/blog/"
# my domain
base_url = "https://guerinpe.com/"
title = "Pierre-Edouard Guerin"
description = "Bioinformatics & Software development"


# The default language, used in RSS
default_language = "en"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#

taxonomies = [
  { name = "tags",  rss = true },
]
# The additional languages for that site
languages = [
    
   
    {code = "fr"},
    {code = "es"} # there won't be a RSS feed for Spannish content
    
]

[extra]
# Put all your custom variables here

webmail = "pierre.edouard.guerin@gmail.com"
myjob_name = "FD"
myjob_site = "https://www.florimond-desprez.com/fr/fr/groupe-florimond-desprez/notre-recherche.html"
mytown = "Lille"
mycountry= "France"
myjob_address= "Site FLORIMOND DESPREZ, 3 Rue Florimond Desprez, 59242 Cappelle-en-Pevele"
myjob_tel="(+33) 04 67 61 32 35"

links = [
    {url = "https://www.linkedin.com/in/pierre-edouard-guerin", name = "linkedin"},
    {url = "https://twitter.com/guerin_pe", name = "twitter"},
    {url = "https://github.com/Grelot", name = "github"},
    {url = "https://gitlab.mbb.univ-montp2.fr/users/peguerin/groups", name = "gitlab"}
]

tags_color = [
    { tech = "#f39c12", sciences = "#e74c3c", omics = "#27ae60" }
    ]

